"""Added new tables

Revision ID: 545ac531517c
Revises: fb6cf1ac4fb6
Create Date: 2023-12-08 02:10:36.125722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545ac531517c'
down_revision: Union[str, None] = 'fb6cf1ac4fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('i_user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interests', 'i_user_id')
    # ### end Alembic commands ###
