"""last tables

Revision ID: 80211fa6c2a8
Revises: b0ef1f7c2096
Create Date: 2023-12-07 00:21:19.617973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80211fa6c2a8'
down_revision: Union[str, None] = 'b0ef1f7c2096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('a_id', sa.UUID(), nullable=False),
    sa.Column('a_user_creator', sa.UUID(), nullable=True),
    sa.Column('a_date', sa.DateTime(), nullable=True),
    sa.Column('a_words', sa.BigInteger(), nullable=True),
    sa.Column('a_decks_full', sa.BigInteger(), nullable=True),
    sa.Column('a_decks_part', sa.BigInteger(), nullable=True),
    sa.Column('a_games', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_table('bankcards',
    sa.Column('bc_user_id', sa.UUID(), nullable=False),
    sa.Column('bc_number', sa.String(length=128), nullable=True),
    sa.Column('bc_cvv', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('bc_user_id')
    )
    op.create_table('decks',
    sa.Column('d_id', sa.UUID(), nullable=False),
    sa.Column('d_creator', sa.UUID(), nullable=True),
    sa.Column('d_name', sa.String(length=128), nullable=True),
    sa.Column('d_description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('d_id')
    )
    op.create_table('groups',
    sa.Column('g_id', sa.UUID(), nullable=False),
    sa.Column('g_name', sa.String(length=128), nullable=True),
    sa.Column('g_admin_id', sa.UUID(), nullable=True),
    sa.Column('g_members', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_table('interests',
    sa.Column('i_id', sa.UUID(), nullable=False),
    sa.Column('i_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('posts',
    sa.Column('p_id', sa.UUID(), nullable=False),
    sa.Column('p_author_id', sa.UUID(), nullable=True),
    sa.Column('p_text', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('socialmediaaccounts',
    sa.Column('sma_id', sa.UUID(), nullable=False),
    sa.Column('sma_user_id', sa.UUID(), nullable=True),
    sa.Column('SMA_type', sa.String(length=128), nullable=True),
    sa.Column('SMA_link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('sma_id')
    )
    op.create_table('users',
    sa.Column('u_id', sa.UUID(), nullable=False),
    sa.Column('u_username', sa.String(length=128), nullable=True),
    sa.Column('u_password', sa.String(length=128), nullable=True),
    sa.Column('u_email', sa.String(length=128), nullable=True),
    sa.Column('u_phone', sa.String(length=128), nullable=True),
    sa.Column('u_country', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('u_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('socialmediaaccounts')
    op.drop_table('posts')
    op.drop_table('interests')
    op.drop_table('groups')
    op.drop_table('decks')
    op.drop_table('bankcards')
    op.drop_table('achievements')
    # ### end Alembic commands ###
