"""Added new tables

Revision ID: b0ef1f7c2096
Revises: 
Create Date: 2023-12-06 23:59:25.271515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ef1f7c2096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('c_id', sa.UUID(), nullable=False),
    sa.Column('c_deck_id', sa.UUID(), nullable=True),
    sa.Column('c_english_word', sa.String(length=128), nullable=True),
    sa.Column('c_translation', sa.String(length=128), nullable=True),
    sa.Column('c_explanation', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('c_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
